functions.c: In function ‘timestamp’:
functions.c:26:30: warning: conversion to ‘double’ from ‘__time_t {aka long int}’ may alter its value [-Wconversion]
     return((double)(tp.tv_sec*1000.0 + tp.tv_usec/1000.0));
                              ^
functions.c:26:50: warning: conversion to ‘double’ from ‘__suseconds_t {aka long int}’ may alter its value [-Wconversion]
     return((double)(tp.tv_sec*1000.0 + tp.tv_usec/1000.0));
                                                  ^
functions.c: In function ‘allocate_vector’:
functions.c:32:61: warning: conversion to ‘long long unsigned int’ from ‘vector_s {aka long long int}’ may change the sign of the result [-Wsign-conversion]
     vector_t *V = (vector_t *)aligned_alloc(ALIGNMENT, size * sizeof(vector_t));
                                                             ^
functions.c: In function ‘get_uncached_mem’:
functions.c:49:20: warning: passing argument 1 of ‘die’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  if (fd == -1) die("couldn't open device");
                    ^~~~~~~~~~~~~~~~~~~~~~
functions.c:37:6: note: expected ‘char *’ but argument is of type ‘const char *’
 void die(char *msg)
      ^~~
functions.c:54:10: warning: conversion to ‘int’ from ‘long int’ may alter its value [-Wconversion]
   size = (size & PAGE_MASK) + PAGE_SIZE;
          ^
functions.c:56:22: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
  void *map = mmap(0, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
                      ^~~~
functions.c:58:7: warning: passing argument 1 of ‘die’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   die("mmap failed.");
       ^~~~~~~~~~~~~~
functions.c:37:6: note: expected ‘char *’ but argument is of type ‘const char *’
 void die(char *msg)
      ^~~
functions.c: In function ‘vectorSum_vec’:
functions.c:120:37: warning: passing argument 1 of ‘_mm256_loadu_si256’ from incompatible pointer type [-Wincompatible-pointer-types]
             va = _mm256_loadu_si256(&V1[i]);
                                     ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:41:0,
                 from functions.c:14:
/usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:920:1: note: expected ‘const __vector(4) long long int *’ but argument is of type ‘vector_t * {aka int *}’
 _mm256_loadu_si256 (__m256i_u const *__P)
 ^~~~~~~~~~~~~~~~~~
functions.c:121:37: warning: passing argument 1 of ‘_mm256_loadu_si256’ from incompatible pointer type [-Wincompatible-pointer-types]
             vb = _mm256_loadu_si256(&V2[i]);
                                     ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:41:0,
                 from functions.c:14:
/usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:920:1: note: expected ‘const __vector(4) long long int *’ but argument is of type ‘vector_t * {aka int *}’
 _mm256_loadu_si256 (__m256i_u const *__P)
 ^~~~~~~~~~~~~~~~~~
functions.c:125:32: warning: passing argument 1 of ‘_mm256_store_si256’ from incompatible pointer type [-Wincompatible-pointer-types]
             _mm256_store_si256(&res[i], sum);
                                ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:41:0,
                 from functions.c:14:
/usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:914:1: note: expected ‘__vector(4) long long int *’ but argument is of type ‘vector_t * {aka int *}’
 _mm256_store_si256 (__m256i *__P, __m256i __A)
 ^~~~~~~~~~~~~~~~~~
functions.c: In function ‘vectorSum_non’:
functions.c:183:43: warning: passing argument 1 of ‘_mm256_stream_load_si256’ from incompatible pointer type [-Wincompatible-pointer-types]
             va = _mm256_stream_load_si256(&V1[i]);
                                           ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:43:0,
                 from functions.c:14:
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx2intrin.h:920:1: note: expected ‘const __vector(4) long long int *’ but argument is of type ‘vector_t * {aka int *}’
 _mm256_stream_load_si256 (__m256i const *__X)
 ^~~~~~~~~~~~~~~~~~~~~~~~
functions.c:184:43: warning: passing argument 1 of ‘_mm256_stream_load_si256’ from incompatible pointer type [-Wincompatible-pointer-types]
             vb = _mm256_stream_load_si256(&V2[i]);
                                           ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:43:0,
                 from functions.c:14:
/usr/lib/gcc/x86_64-linux-gnu/7/include/avx2intrin.h:920:1: note: expected ‘const __vector(4) long long int *’ but argument is of type ‘vector_t * {aka int *}’
 _mm256_stream_load_si256 (__m256i const *__X)
 ^~~~~~~~~~~~~~~~~~~~~~~~
functions.c:188:32: warning: passing argument 1 of ‘_mm256_store_si256’ from incompatible pointer type [-Wincompatible-pointer-types]
             _mm256_store_si256(&res[i], sum);
                                ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:41:0,
                 from functions.c:14:
/usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:914:1: note: expected ‘__vector(4) long long int *’ but argument is of type ‘vector_t * {aka int *}’
 _mm256_store_si256 (__m256i *__P, __m256i __A)
 ^~~~~~~~~~~~~~~~~~
functions.c: In function ‘die’:
functions.c:37:6: warning: function might be candidate for attribute ‘noreturn’ [-Wsuggest-attribute=noreturn]
 void die(char *msg)
      ^~~
lfsr.c: In function ‘shift_lfsr’:
lfsr.c:29:9: warning: conversion to ‘int’ from ‘uint {aka unsigned int}’ may change the sign of the result [-Wsign-conversion]
  return *lfsr;
         ^~~~~
vectorSum.c: In function ‘main’:
vectorSum.c:82:30: warning: conversion to ‘long long unsigned int’ from ‘vector_s {aka long long int}’ may change the sign of the result [-Wsign-conversion]
   vector_size = vector_bytes / sizeof(vector_t);
                              ^
vectorSum.c:82:17: warning: conversion to ‘vector_s {aka long long int}’ from ‘long long unsigned int’ may change the sign of the result [-Wsign-conversion]
   vector_size = vector_bytes / sizeof(vector_t);
                 ^~~~~~~~~~~~
