functions.c: In function ‘timestamp’:
functions.c:24:30: warning: conversion to ‘double’ from ‘__time_t {aka long int}’ may alter its value [-Wconversion]
     return((double)(tp.tv_sec*1000.0 + tp.tv_usec/1000.0));
                              ^
functions.c:24:50: warning: conversion to ‘double’ from ‘__suseconds_t {aka long int}’ may alter its value [-Wconversion]
     return((double)(tp.tv_sec*1000.0 + tp.tv_usec/1000.0));
                                                  ^
functions.c: In function ‘allocate_vector’:
functions.c:30:61: warning: conversion to ‘long long unsigned int’ from ‘vector_s {aka long long int}’ may change the sign of the result [-Wsign-conversion]
     vector_t *V = (vector_t *)aligned_alloc(ALIGNMENT, size * sizeof(vector_t));
                                                             ^
functions.c: In function ‘get_uncached_mem’:
functions.c:47:20: warning: passing argument 1 of ‘die’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  if (fd == -1) die("couldn't open device");
                    ^~~~~~~~~~~~~~~~~~~~~~
functions.c:35:6: note: expected ‘char *’ but argument is of type ‘const char *’
 void die(char *msg)
      ^~~
functions.c:52:10: warning: conversion to ‘int’ from ‘long int’ may alter its value [-Wconversion]
   size = (size & PAGE_MASK) + PAGE_SIZE;
          ^
functions.c:54:22: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
  void *map = mmap(0, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
                      ^~~~
functions.c:56:7: warning: passing argument 1 of ‘die’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   die("mmap failed.");
       ^~~~~~~~~~~~~~
functions.c:35:6: note: expected ‘char *’ but argument is of type ‘const char *’
 void die(char *msg)
      ^~~
functions.c: In function ‘predicate’:
functions.c:120:36: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
             base = _mm_loadu_si128(&base_vec[i]);
                                    ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/xmmintrin.h:1252:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:29,
                 from functions.c:14:
/usr/lib/gcc/x86_64-linux-gnu/7/include/emmintrin.h:701:1: note: expected ‘const __vector(2) long long int *’ but argument is of type ‘vector_t * {aka int *}’
 _mm_loadu_si128 (__m128i_u const *__P)
 ^~~~~~~~~~~~~~~
functions.c:121:36: warning: passing argument 1 of ‘_mm_loadu_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
             vcmp = _mm_loadu_si128(&vec_cmp[i]);
                                    ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/xmmintrin.h:1252:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:29,
                 from functions.c:14:
/usr/lib/gcc/x86_64-linux-gnu/7/include/emmintrin.h:701:1: note: expected ‘const __vector(2) long long int *’ but argument is of type ‘vector_t * {aka int *}’
 _mm_loadu_si128 (__m128i_u const *__P)
 ^~~~~~~~~~~~~~~
functions.c:103:69: warning: unused parameter ‘res’ [-Wunused-parameter]
 vector_s predicate(vector_t *base_vec, vector_t *vec_cmp, vector_t *res, vector_s size, long long int value, int stride)
                                                                     ^~~
functions.c:103:103: warning: unused parameter ‘value’ [-Wunused-parameter]
 vector_s predicate(vector_t *base_vec, vector_t *vec_cmp, vector_t *res, vector_s size, long long int value, int stride)
                                                                                                       ^~~~~
functions.c: In function ‘predicate_nt’:
functions.c:225:42: warning: passing argument 1 of ‘_mm_stream_load_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
             base = _mm_stream_load_si128(&base_vec[i]);
                                          ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:37:0,
                 from functions.c:14:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:582:1: note: expected ‘__vector(2) long long int *’ but argument is of type ‘vector_t * {aka int *}’
 _mm_stream_load_si128 (__m128i *__X)
 ^~~~~~~~~~~~~~~~~~~~~
functions.c:226:42: warning: passing argument 1 of ‘_mm_stream_load_si128’ from incompatible pointer type [-Wincompatible-pointer-types]
             vcmp = _mm_stream_load_si128(&vec_cmp[i]);
                                          ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:37:0,
                 from functions.c:14:
/usr/lib/gcc/x86_64-linux-gnu/7/include/smmintrin.h:582:1: note: expected ‘__vector(2) long long int *’ but argument is of type ‘vector_t * {aka int *}’
 _mm_stream_load_si128 (__m128i *__X)
 ^~~~~~~~~~~~~~~~~~~~~
functions.c:208:72: warning: unused parameter ‘res’ [-Wunused-parameter]
 vector_s predicate_nt(vector_t *base_vec, vector_t *vec_cmp, vector_t *res, vector_s size, long long int value, int stride)
                                                                        ^~~
functions.c:208:106: warning: unused parameter ‘value’ [-Wunused-parameter]
 vector_s predicate_nt(vector_t *base_vec, vector_t *vec_cmp, vector_t *res, vector_s size, long long int value, int stride)
                                                                                                          ^~~~~
functions.c: In function ‘die’:
functions.c:35:6: warning: function might be candidate for attribute ‘noreturn’ [-Wsuggest-attribute=noreturn]
 void die(char *msg)
      ^~~
lfsr.c: In function ‘shift_lfsr’:
lfsr.c:29:9: warning: conversion to ‘int’ from ‘uint {aka unsigned int}’ may change the sign of the result [-Wsign-conversion]
  return *lfsr;
         ^~~~~
lfsr.c: In function ‘get_random’:
lfsr.c:44:81: warning: conversion to ‘int’ from ‘long long int’ may alter its value [-Wconversion]
  return((shift_lfsr(&lfsr32, POLY_MASK_32) ^ shift_lfsr(&lfsr31, POLY_MASK_31)) & range);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
predication.c: In function ‘main’:
predication.c:93:30: warning: conversion to ‘long long unsigned int’ from ‘vector_s {aka long long int}’ may change the sign of the result [-Wsign-conversion]
   vector_size = vector_bytes / sizeof(vector_t);
                              ^
predication.c:93:17: warning: conversion to ‘vector_s {aka long long int}’ from ‘long long unsigned int’ may change the sign of the result [-Wsign-conversion]
   vector_size = vector_bytes / sizeof(vector_t);
                 ^~~~~~~~~~~~
predication.c:38:54: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
   vector_s vector_size, vector_bytes, i, iterations, result;
                                                      ^~~~~~
