functions.c: In function ‘timestamp’:
functions.c:26:30: warning: conversion to ‘double’ from ‘__time_t {aka long int}’ may alter its value [-Wconversion]
     return((double)(tp.tv_sec*1000.0 + tp.tv_usec/1000.0));
                              ^
functions.c:26:50: warning: conversion to ‘double’ from ‘__suseconds_t {aka long int}’ may alter its value [-Wconversion]
     return((double)(tp.tv_sec*1000.0 + tp.tv_usec/1000.0));
                                                  ^
functions.c: In function ‘allocate_vector’:
functions.c:32:61: warning: conversion to ‘long long unsigned int’ from ‘vector_s {aka long long int}’ may change the sign of the result [-Wsign-conversion]
     vector_t *V = (vector_t *)aligned_alloc(ALIGNMENT, size * sizeof(vector_t));
                                                             ^
functions.c: In function ‘get_uncached_mem’:
functions.c:49:20: warning: passing argument 1 of ‘die’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  if (fd == -1) die("couldn't open device");
                    ^~~~~~~~~~~~~~~~~~~~~~
functions.c:37:6: note: expected ‘char *’ but argument is of type ‘const char *’
 void die(char *msg)
      ^~~
functions.c:54:10: warning: conversion to ‘int’ from ‘long int’ may alter its value [-Wconversion]
   size = (size & PAGE_MASK) + PAGE_SIZE;
          ^
functions.c:56:22: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
  void *map = mmap(0, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
                      ^~~~
functions.c:58:7: warning: passing argument 1 of ‘die’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   die("mmap failed.");
       ^~~~~~~~~~~~~~
functions.c:37:6: note: expected ‘char *’ but argument is of type ‘const char *’
 void die(char *msg)
      ^~~
functions.c: In function ‘vectorSum_vec’:
functions.c:131:33: warning: conversion to ‘long long unsigned int’ from ‘vector_s {aka long long int}’ may change the sign of the result [-Wsign-conversion]
         for (i = 0; i < size; i += STRIDE)
                                 ^~
In file included from functions.c:16:0:
functions.h:7:16: warning: conversion to ‘vector_s {aka long long int}’ from ‘long long unsigned int’ may change the sign of the result [-Wsign-conversion]
 #define STRIDE 512/(sizeof(vector_t) * 8)
                ^
functions.c:131:36: note: in expansion of macro ‘STRIDE’
         for (i = 0; i < size; i += STRIDE)
                                    ^~~~~~
functions.c: In function ‘vectorSum_non’:
functions.c:188:33: warning: conversion to ‘long long unsigned int’ from ‘vector_s {aka long long int}’ may change the sign of the result [-Wsign-conversion]
         for (i = 0; i < size; i += STRIDE)
                                 ^~
In file included from functions.c:16:0:
functions.h:7:16: warning: conversion to ‘vector_s {aka long long int}’ from ‘long long unsigned int’ may change the sign of the result [-Wsign-conversion]
 #define STRIDE 512/(sizeof(vector_t) * 8)
                ^
functions.c:188:36: note: in expansion of macro ‘STRIDE’
         for (i = 0; i < size; i += STRIDE)
                                    ^~~~~~
functions.c: In function ‘die’:
functions.c:37:6: warning: function might be candidate for attribute ‘noreturn’ [-Wsuggest-attribute=noreturn]
 void die(char *msg)
      ^~~
lfsr.c: In function ‘shift_lfsr’:
lfsr.c:29:9: warning: conversion to ‘int’ from ‘uint {aka unsigned int}’ may change the sign of the result [-Wsign-conversion]
  return *lfsr;
         ^~~~~
vectorSum.c: In function ‘main’:
vectorSum.c:81:30: warning: conversion to ‘long long unsigned int’ from ‘vector_s {aka long long int}’ may change the sign of the result [-Wsign-conversion]
   vector_size = vector_bytes / sizeof(vector_t);
                              ^
vectorSum.c:81:17: warning: conversion to ‘vector_s {aka long long int}’ from ‘long long unsigned int’ may change the sign of the result [-Wsign-conversion]
   vector_size = vector_bytes / sizeof(vector_t);
                 ^~~~~~~~~~~~
vectorSum.c:96:32: warning: conversion to ‘int’ from ‘vector_s {aka long long int}’ may alter its value [-Wconversion]
   map1 = get_uncached_mem(dev, vector_bytes);
                                ^~~~~~~~~~~~
vectorSum.c:97:32: warning: conversion to ‘int’ from ‘vector_s {aka long long int}’ may alter its value [-Wconversion]
   map2 = get_uncached_mem(dev, vector_bytes);
                                ^~~~~~~~~~~~
vectorSum.c:98:32: warning: conversion to ‘int’ from ‘vector_s {aka long long int}’ may alter its value [-Wconversion]
   map3 = get_uncached_mem(dev, vector_bytes);
                                ^~~~~~~~~~~~
